name: Deploy Astro to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'src/**'
      - 'dist/**'
      - 'public/**'
      - '.github/workflows/deploy.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'  # o '22.x', '22.12.0', etc.

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - uses: actions/deploy-pages@v4
